-- MySQL Script generated by MySQL Workbench
-- Sun Jan 13 10:41:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock` ;
USE `stock` ;

-- -----------------------------------------------------
-- Table `stock`.`stock_base_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`stock_base_info` (
  `trade_date` VARCHAR(45) NOT NULL,
  `ts_code` VARCHAR(45) NOT NULL,
  `open` DOUBLE NULL,
  `close` DOUBLE NULL,
  `high` DOUBLE NULL,
  `low` DOUBLE NULL,
  `vol` DOUBLE NULL,
  `amount` DOUBLE NULL,
  `pre_close` DOUBLE NULL,
  `change` DOUBLE NULL,
  `pct_chg` DOUBLE NULL,
  PRIMARY KEY (`trade_date`, `ts_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`stock_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`stock_list` (
  `ts_code` VARCHAR(20) NOT NULL,
  `symbol` VARCHAR(20) NULL,
  `name` VARCHAR(20) NULL,
  `area` VARCHAR(45) NULL,
  `industry` VARCHAR(45) NULL,
  `fullname` VARCHAR(45) NULL,
  `enname` VARCHAR(45) NULL,
  `market` VARCHAR(45) NULL,
  `list_status` VARCHAR(45) NULL,
  `list_date` VARCHAR(45) NULL,
  `delist_date` VARCHAR(45) NULL,
  `is_hs` VARCHAR(45) NULL,
  `exchange` VARCHAR(45) NULL,
  `curr_type` VARCHAR(45) NULL,
  PRIMARY KEY (`ts_code`),
  INDEX `code_index` (`symbol` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`adj_factor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`adj_factor` (
  `ts_code` VARCHAR(45) NOT NULL,
  `trade_date` VARCHAR(45) NOT NULL,
  `adj_factor` DOUBLE NULL,
  PRIMARY KEY (`ts_code`, `trade_date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`stock_adj_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`stock_adj_info` (
  `ts_code` VARCHAR(45) NOT NULL,
  `trade_date` VARCHAR(45) NOT NULL,
  `open` DOUBLE NULL,
  `close` DOUBLE NULL,
  `high` DOUBLE NULL,
  `low` DOUBLE NULL,
  `amount` DOUBLE NULL,
  `vol` DOUBLE NULL,
  `pre_close` DOUBLE NULL,
  `change` DOUBLE NULL,
  `pct_change` DOUBLE NULL,
  PRIMARY KEY (`ts_code`, `trade_date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock`.`stock_index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock`.`stock_index` (
  `ts_code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NULL,
  `fullname` VARCHAR(80) NULL,
  `market` VARCHAR(45) NULL,
  `publisher` VARCHAR(45) NULL,
  `index_type` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `base_date` VARCHAR(45) NULL,
  `base_point` DOUBLE NULL,
  `list_date` VARCHAR(45) NULL,
  `weight_rule` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `exp_date` VARCHAR(45) NULL,
  PRIMARY KEY (`ts_code`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
